name: Tests
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-em/bootstrap-lix@168bf411886966879dd3106ee48902c6bac38cb1
      - run: nix --version 2>&1 | grep "Lix, like Nix"
